name: Extract Data

on:
  # Run on schedule (every 6 hours)
  schedule:
    - cron: '0 */6 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5

      - name: Clone external repository
        run: |
          git clone https://github.com/drawthingsai/community-models.git
          ls community-models  

      - name: Install node.js
        uses: actions/setup-node@v6
        with: 
          node-version: 24

      - name: Install npm dependencies
        working-directory: /home/runner/work/drawthings-community-models-extract/drawthings-community-models-extract/app
        run: |
          pwd
          npm install

      - name: Run node.js app
        working-directory: /home/runner/work/drawthings-community-models-extract/drawthings-community-models-extract/app
        run: |
          pwd  
          node app.js        
          
      - name: Git commit back 2x data files
        working-directory: /home/runner/work/drawthings-community-models-extract/drawthings-community-models-extract/app
        run: |
          ls 
          git status


