---
name: Sync External Repository

on:
  # Run on schedule (every 6 hours)
  schedule:
    - cron: '0 */6 * * *'

  # Allow manual trigger
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clone external repository
        run: |
          git clone https://github.com/drawthingsai/community-models.git
          ls community-models  


      # - name: Commit and push changes
      #   run: |
      #     git config --local \
      #       user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add -A
      #     if ! git diff --staged --quiet; then
      #       git commit -m "Update data extracts from external repository"
      #       git push
      #     else
      #       echo "No changes to commit"
      #     fi
