---
name: Sync External Repository

on:
  # Run on schedule (every 6 hours)
  schedule:
    - cron: '0 */6 * * *'

  # Allow manual trigger
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5
        with:
          path: main

      - name: Clone external repository
        run: |
          git clone https://github.com/drawthingsai/community-models.git
          ls community-models  

      - name: Install node.js
        uses: actions/setup-node@v6
        with: 
          node-version: 24
      
      - name: Install npm dependencies
        run: |
          cd app
          npm install




